/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input usb_rx,
    output reg usb_tx,
    input [7:0] pdm_data_in,
    output reg [7:0] pdm_clock_out,
    output reg [31:0] fx3_dq,
    output reg fx3_pclk,
    output reg fx3_slcs_,
    output reg fx3_slwr_,
    output reg fx3_sloe_,
    output reg fx3_slrd_,
    output reg fx3_pktend_,
    input fx3_flaga,
    input fx3_flagb,
    input fx3_flagc,
    input fx3_flagd,
    output reg [1:0] fx3_a
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  reg [7:0] M_sample_counter_d, M_sample_counter_q = 1'h0;
  reg [7:0] M_sample_d, M_sample_q = 1'h0;
  reg M_booting_d, M_booting_q = 1'h0;
  reg [7:0] M_cycle_d, M_cycle_q = 1'h0;
  reg M_mic_clock_d, M_mic_clock_q = 1'h0;
  reg [31:0] M_bootcounter_d, M_bootcounter_q = 1'h0;
  
  always @* begin
    M_bootcounter_d = M_bootcounter_q;
    M_sample_counter_d = M_sample_counter_q;
    M_cycle_d = M_cycle_q;
    M_sample_d = M_sample_q;
    M_booting_d = M_booting_q;
    M_mic_clock_d = M_mic_clock_q;
    
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    usb_tx = usb_rx;
    pdm_clock_out = {4'h8{M_mic_clock_q}};
    if (M_booting_q == 1'h0) begin
      fx3_dq = 1'h0;
      fx3_a = 2'h0;
      fx3_slcs_ = 1'h0;
      fx3_slrd_ = 1'h0;
      fx3_sloe_ = 1'h0;
      fx3_pclk = 1'h0;
      fx3_pktend_ = 1'h0;
      fx3_slwr_ = 1'h0;
      M_bootcounter_d = M_bootcounter_q + 1'h1;
      if (M_bootcounter_q == 29'h17d78400) begin
        M_booting_d = 1'h1;
      end
    end else begin
      fx3_a = 2'h0;
      fx3_slcs_ = 1'h0;
      fx3_slrd_ = 1'h1;
      fx3_sloe_ = 1'h1;
      fx3_pclk = clk;
      fx3_pktend_ = 1'h1;
      M_cycle_d = M_cycle_q + 1'h1;
      if (M_cycle_q == 4'hf) begin
        M_mic_clock_d = 1'h0;
      end
      if (M_cycle_q == 5'h1d) begin
        M_sample_d = pdm_data_in;
      end
      fx3_slwr_ = 1'h1;
      if (M_cycle_q == 5'h1e) begin
        fx3_slwr_ = 1'h0;
      end
      if (M_cycle_q == 5'h1f) begin
        M_mic_clock_d = 1'h1;
        M_cycle_d = 1'h0;
        M_sample_counter_d = M_sample_counter_q + 1'h1;
      end
      fx3_dq = {M_cycle_q, M_sample_counter_q, 8'h00, M_sample_q};
    end
    led = {4'h8{M_booting_q}};
  end
  
  always @(posedge clk) begin
    M_sample_counter_q <= M_sample_counter_d;
    M_sample_q <= M_sample_d;
    M_booting_q <= M_booting_d;
    M_cycle_q <= M_cycle_d;
    M_mic_clock_q <= M_mic_clock_d;
    M_bootcounter_q <= M_bootcounter_d;
  end
  
endmodule
