/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module pdm_mics_2 (
    input clk,
    input rst,
    output reg mic_clk,
    input [7:0] mic_data,
    output reg [7:0] sample,
    output reg new_sample
  );
  
  
  
  wire [4-1:0] M_clk_ctr_value;
  counter_5 clk_ctr (
    .clk(clk),
    .rst(rst),
    .value(M_clk_ctr_value)
  );
  reg M_mic_clk_reg_d, M_mic_clk_reg_q = 1'h0;
  wire [1-1:0] M_clk_edge_out;
  reg [1-1:0] M_clk_edge_in;
  edge_detector_6 clk_edge (
    .clk(clk),
    .in(M_clk_edge_in),
    .out(M_clk_edge_out)
  );
  reg [7:0] M_sample_register_d, M_sample_register_q = 1'h0;
  reg M_sample_ready_d, M_sample_ready_q = 1'h0;
  
  always @* begin
    M_mic_clk_reg_d = M_mic_clk_reg_q;
    M_sample_register_d = M_sample_register_q;
    M_sample_ready_d = M_sample_ready_q;
    
    M_clk_edge_in = M_clk_ctr_value[3+0-:1];
    if (M_clk_edge_out) begin
      M_mic_clk_reg_d = ~M_mic_clk_reg_q;
    end
    mic_clk = M_mic_clk_reg_q;
    M_sample_ready_d = 1'h0;
    if (M_mic_clk_reg_q == 1'h0 && M_clk_edge_out) begin
      M_sample_register_d = mic_data;
      M_sample_ready_d = 1'h1;
    end
    new_sample = M_sample_ready_q;
    sample = M_sample_register_q;
  end
  
  always @(posedge clk) begin
    M_sample_register_q <= M_sample_register_d;
    M_sample_ready_q <= M_sample_ready_d;
    
    if (rst == 1'b1) begin
      M_mic_clk_reg_q <= 1'h0;
    end else begin
      M_mic_clk_reg_q <= M_mic_clk_reg_d;
    end
  end
  
endmodule
